SELECT * FROM S_SALES;

--FINDING THE BEST PERFORMING BRANCH
SELECT COUNT(BRANCH) AS MOST_REPEATING_BRANCH, BRANCH, CITY
FROM S_SALES
GROUP BY BRANCH, CITY
ORDER BY MOST_REPEATING_BRANCH DESC;

--FINDING IF MEMBERS PURCHASE MORE THAN NORMAL CUSTOMERS
SELECT COUNT(CUSTOMERTYPE), CUSTOMERTYPE FROM S_SALES
GROUP BY CUSTOMERTYPE;


--BEST PERFOMRING PRODUCTLINE
SELECT COUNT(PRODUCTLINE) AS PRODUCTLINE_COUNT, PRODUCTLINE FROM S_SALES
GROUP BY PRODUCTLINE
ORDER BY PRODUCTLINE_COUNT DESC;

--PRODUCTLINE THAT GIVES THE BEST GROSS INCOME
SELECT SUM(COGS) AS TOTAL_OF_GOODS_SOLD, PRODUCTLINE
FROM S_SALES
GROUP BY PRODUCTLINE
ORDER BY TOTAL_OF_GOODS_SOLD DESC

--BEST PERFORMING PRODUCTLINE AS PER CITIES AS PER COGS
WITH TOTAL_OF_COGS AS(
SELECT SUM(COGS) AS TOTAL_OF_COGS,
CITY,
BRANCH,
PRODUCTLINE
FROM S_SALES
GROUP BY 
CITY, 
BRANCH,
PRODUCTLINE
),
MAX_OF_COGS AS (
SELECT TOTAL_OF_COGS,
CITY,
BRANCH,
PRODUCTLINE,
ROW_NUMBER() OVER (
PARTITION BY CITY ORDER BY TOTAL_OF_COGS DESC
) AS RANK 
FROM TOTAL_OF_COGS
)
SELECT TOTAL_OF_COGS,
CITY,
BRANCH,
PRODUCTLINE 
FROM MAX_OF_COGS
WHERE
RANK = 1
ORDER BY 
    TOTAL_OF_COGS DESC;

--BUYING PATTERN BASED ON THE GENDER
SELECT COUNT(GENDER) AS MALE_PREFERENCES, PRODUCTLINE 
FROM S_SALES
WHERE GENDER = 'MALE'
GROUP BY PRODUCTLINE
ORDER BY MALE_PREFERENCES DESC


SELECT COUNT(GENDER) AS FEMALE_PREFERENCES, PRODUCTLINE 
FROM S_SALES
WHERE GENDER = 'FEMALE'
GROUP BY GENDER, PRODUCTLINE
ORDER BY FEMALE_PREFERENCES DESC;

--FINDING MAXIMUM PRICE OF A PRODUCT
SELECT MAX(COGS) AS MAXIMUM_BILL_AMOUNT, PRODUCTLINE, QUANTITY
FROM S_SALES
WHERE QUANTITY = '1'
GROUP BY PRODUCTLINE, QUANTITY

--FINDING MINIMUM PRICE OF A PRODUCT
SELECT MIN(COGS) AS MAXIMUM_BILL_AMOUNT, PRODUCTLINE, QUANTITY
FROM S_SALES
WHERE QUANTITY = '1'
GROUP BY PRODUCTLINE, QUANTITY

--FINDING THE PRODUCTLINE THAT HAS THE HIGHEST RATING
SELECT MAX(RATING) AS MAX_RATING, PRODUCTLINE
FROM S_SALES
GROUP BY PRODUCTLINE
ORDER BY MAX_RATING DESC

--FINDING THE MOST PREFERRED PAYMENT METHOD
SELECT COUNT(PAYMENT) AS MOST_PREFERRED_PAYMENT, PAYMENT
FROM S_SALES
GROUP BY PAYMENT;


-- Step 1: Add the new column
ALTER TABLE S_SALES
ADD AVERAGE_RATING DECIMAL(5,2);

-- Step 2: Update the AVERAGE_RATING column using a JOIN
UPDATE S_SALES
SET AVERAGE_RATING = avg_ratings.AVERAGE_RATING
FROM S_SALES
JOIN (
    SELECT PRODUCTLINE, AVG(RATING) AS AVERAGE_RATING
    FROM S_SALES
    GROUP BY PRODUCTLINE
) AS avg_ratings
ON S_SALES.PRODUCTLINE = avg_ratings.PRODUCTLINE;









